.Dd 2/11/11
.Dt SigmaVPN
.Sh NAME
.Nm naclkeypair
.Nd A toolkit to built naclkeypair
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
is a toolkit to create public and private keypair used by nacltai proto.
.Pp
.Sh SEE ALSO
Google Code:
.Ar http://code.google.com/p/sigmavpn/
Github:
.Ar http://github.com/neilalexander/sigmavpn/
.Sh AUTHOR
Neil Alexander T <neilalexander@frozenriver.net>, with contributions from Ivo Smits <ivo@ufo-net.nl>.
